
language: r
cache: packages
warnings_are_errors: false
notifications:
  email:
    on_success: change
    on_failure: change
matrix:
  include:
  - r:
  -     oldrel
  -     release
  -     devel
 - r: release
    os: osx
    osx_image: xcode7.3

