language: r
cache: packages
warnings_are_errors: false


matrix:
  include:
    - dist: trusty
      r:
         - oldrel
         - release
         - devel
    - dist: xenial
      r:
         - oldrel
         - release
         - devel
    - dist: bionic
      r:
         - oldrel
         - release
         - devel
    - os: osx
      r:
         - oldrel
         - release
         - devel
      osx_image: xcode11.3

notifications:
  email:
    on_success: change
    on_failure: change
  slack: speechdev:fxNJNl9oIJ9Ay9sjk9am26Bw