language: r
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - dist: bionic
    - os: osx
      osx_image: xcode11.3

notifications:
  email:
    on_success: change
    on_failure: change
  slack: speechdev:fxNJNl9oIJ9Ay9sjk9am26Bw