
language: R
cache: packages
warnings_are_errors: false
notifications:
  email:
    on_success: change
    on_failure: change
matrix:
  include:
  - r: release
  - r: release
    os: osx
    osx_image: xcode9.2

